pipeline {
   agent any
   stages{
      stage('Build'){
          steps {
             dir('JSPSample'){
               sh 'mvn clean package'
                sh "docker build . -t tomcatwebapp:${env.BUILD_ID}" 
             }
          }
       }
   }
}    
   
